version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${HOST_PORT}:5432
  web_app:
    build: .
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./file_storage/data:/app/file_storage/data
    depends_on:
      - "postgres"
