version: "3"

volumes:
  file_storage:
  temp_data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
  web_app:
    build: .
    volumes:
      - file_storage/data/
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - 5000:5000
    depends_on:
      - "postgres"
